### PR TITLE
Update OrientDBBinaryConnection.cs

### PR DESCRIPTION
**Pull request by alzuma**
https://github.com/orientechnologies/OrientDB.Net.Core/issues/8

### CODE REVIEW

**Comment by weizensnake** [comment]
Thanks for doing that!

**Comment by realityenigma** [comment]
ty

**Comment by mike-echo-oscar-whiskey** [comment]
when will this be in a release on nuget?

**Comment by realityenigma** [comment]
It already should already be, also note, as recommended by others within the community, I've merged all the core projects into a single solution located at: https://github.com/orientechnologies/OrientDB.Net.git. This is to help speed up development by not having to wait on nugets to be published.

**Pull request merged**
